dataset:
  name: "CIFAR100"
  in_channels: 3
  img_size: 32
  num_classes: 100

training:
  batch_size: 64
  lr: 0.001
  epochs: 70
  weight_decay: 0.05

model:
  name: "CIFAR100-ViT-CNN"
  embed_dim: 192
  depth: 12
  num_heads: 12
  mlp_ratio: 4.0

  patch_embedding:
    type: "cnn"
    size: 4
    kernel_size: 3

  token_injection:
    type: "cls"

  positional_encoding:
    type: "absolute"

  aggregation:
    type: "cls"  
