dataset:
  name: "MNIST"
  in_channels: 1  # Para PatchEmbedding
  img_size: 28    # Para PatchEmbedding

training:
  batch_size: 64
  lr: 0.001
  epochs: 5
  weight_decay: 0.05

model:
  name: "MNIST-ViTBase"
  embed_dim: 128 # Para PatchEmbedding, PositionalEncoding, TokenInjection
  # Resto de hiperparámetros (num_heads, depth, etc.)

  patch_embedding:
    type: "vanilla"
    size: 7

  token_injection:
    type: "cls"

  positional_encoding:
    type: "learnable"
    # num_tokens: ¿Lo calculamos o que lo calcule el usuario y lo ponga?

  aggregation:
    type: "cls"  

  attention:
    # ... Futuros parámetros para introducir rotaciones
